// Code generated by hertz generator.

package handler

import (
	"context"
	"gitlab.aiecnu.net/elion/elion-reading-post/infra/config"
	"gitlab.aiecnu.net/elion/elion-reading-post/post"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}

// Unabandon /unabandon?id=x [Get]
func Unabandon(ctx context.Context, c *app.RequestContext) {
	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{"message": "id format err:" + err.Error()})
		return
	}
	c.JSON(consts.StatusOK, utils.H{
		"message": post.GetManager(config.GetConfig().Consumers).Unabandon(id),
	})
}
